/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointPersonInfoWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointPersonInfoWrapper (0 custom class methods, 4 custom properties)

#import "GTLPersonendpointPersonInfoWrapper.h"

#import "GTLPersonendpointDeviceInfo.h"
#import "GTLPersonendpointPersonCards.h"
#import "GTLPersonendpointPersonCredentials.h"
#import "GTLPersonendpointPersonProfile.h"

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointPersonInfoWrapper
//

@implementation GTLPersonendpointPersonInfoWrapper
@dynamic deviceInfo, personCardsList, personCredentials, personProfile;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLPersonendpointPersonCards class]
                                forKey:@"personCardsList"];
  return map;
}

@end
