/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointPersonCards.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointPersonCards (0 custom class methods, 6 custom properties)

#import "GTLPersonendpointPersonCards.h"

#import "GTLPersonendpointPersonProfile.h"

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointPersonCards
//

@implementation GTLPersonendpointPersonCards
@dynamic card4DigitNum, cardExp, cardType, identifier, owner, secureToken;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
