/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API

#import "GTLPersonendpointConstants.h"

#import "GTLPersonendpointBooleanWrapper.h"
#import "GTLPersonendpointDeviceInfo.h"
#import "GTLPersonendpointPersonCards.h"
#import "GTLPersonendpointPersonCardsListWrapper.h"
#import "GTLPersonendpointPersonCredentials.h"
#import "GTLPersonendpointPersonInfoWrapper.h"
#import "GTLPersonendpointPersonProfile.h"

#import "GTLQueryPersonendpoint.h"
#import "GTLServicePersonendpoint.h"
