/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointBooleanWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointBooleanWrapper (0 custom class methods, 1 custom properties)

#import "GTLPersonendpointBooleanWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointBooleanWrapper
//

@implementation GTLPersonendpointBooleanWrapper
@dynamic boolValue;
@end
