/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointPersonCards.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointPersonCards (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLPersonendpointPersonProfile;

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointPersonCards
//

@interface GTLPersonendpointPersonCards : GTLObject
@property (copy) NSString *card4DigitNum;
@property (retain) NSNumber *cardExp;  // longLongValue
@property (copy) NSString *cardType;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) GTLPersonendpointPersonProfile *owner;
@property (copy) NSString *secureToken;
@end
