/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointPersonCardsListWrapper.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointPersonCardsListWrapper (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLPersonendpointPersonCards;

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointPersonCardsListWrapper
//

@interface GTLPersonendpointPersonCardsListWrapper : GTLObject
@property (retain) NSArray *cardList;  // of GTLPersonendpointPersonCards
@end
