/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointPersonProfile.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointPersonProfile (0 custom class methods, 9 custom properties)

#import "GTLPersonendpointPersonProfile.h"

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointPersonProfile
//

@implementation GTLPersonendpointPersonProfile
@dynamic city, createdDate, identifier, modifiedDate, name, phone, state,
         streetAddress, zip;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
