/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API

#import "GTLPersonendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopePersonendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
