/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointDeviceInfo.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointDeviceInfo (0 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLPersonendpointPersonProfile;

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointDeviceInfo
//

@interface GTLPersonendpointDeviceInfo : GTLObject
@property (retain) NSNumber *createdDate;  // longLongValue
@property (copy) NSString *deviceFormFactor;
@property (copy) NSString *deviceGCMRegistrationId;
@property (copy) NSString *deviceMACAddress;
@property (copy) NSString *deviceManufacturer;
@property (copy) NSString *deviceOS;
@property (copy) NSString *deviceOSVersion;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (retain) GTLPersonendpointPersonProfile *owner;
@end
