/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointPersonCredentials.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointPersonCredentials (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLPersonendpointPersonProfile;

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointPersonCredentials
//

@interface GTLPersonendpointPersonCredentials : GTLObject
@property (retain) NSNumber *createdDate;  // longLongValue
@property (copy) NSString *email;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *loginProviderType;  // intValue
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (retain) GTLPersonendpointPersonProfile *owner;
@property (copy) NSString *profilePhotoUrl;
@property (copy) NSString *token;
@property (copy) NSString *userId;
@end
