/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointDeviceInfo.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointDeviceInfo (0 custom class methods, 10 custom properties)

#import "GTLPersonendpointDeviceInfo.h"

#import "GTLPersonendpointPersonProfile.h"

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointDeviceInfo
//

@implementation GTLPersonendpointDeviceInfo
@dynamic createdDate, deviceFormFactor, deviceGCMRegistrationId,
         deviceMACAddress, deviceManufacturer, deviceOS, deviceOSVersion,
         identifier, modifiedDate, owner;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
