/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointPersonInfoWrapper.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointPersonInfoWrapper (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLPersonendpointDeviceInfo;
@class GTLPersonendpointPersonCards;
@class GTLPersonendpointPersonCredentials;
@class GTLPersonendpointPersonProfile;

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointPersonInfoWrapper
//

@interface GTLPersonendpointPersonInfoWrapper : GTLObject
@property (retain) GTLPersonendpointDeviceInfo *deviceInfo;
@property (retain) NSArray *personCardsList;  // of GTLPersonendpointPersonCards
@property (retain) GTLPersonendpointPersonCredentials *personCredentials;
@property (retain) GTLPersonendpointPersonProfile *personProfile;
@end
