/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryPersonendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryPersonendpoint (8 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLPersonendpointDeviceInfo;
@class GTLPersonendpointPersonCardsListWrapper;
@class GTLPersonendpointPersonInfoWrapper;

@interface GTLQueryPersonendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *email;
@property (copy) NSString *gcmMessage;
@property (copy) NSString *gcmRegistrationId;
@property (copy) NSString *password;
@property (assign) long long personId;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryPersonendpoint object.

// Method: personendpoint.getDeviceInfoByGCMRegistrationId
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointDeviceInfo.
+ (id)queryForGetDeviceInfoByGCMRegistrationIdWithGcmRegistrationId:(NSString *)gcmRegistrationId;

// Method: personendpoint.nativeLogin
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointPersonInfoWrapper.
+ (id)queryForNativeLoginWithObject:(GTLPersonendpointDeviceInfo *)object
                              email:(NSString *)email
                           password:(NSString *)password;

// Method: personendpoint.nativeSignup
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointPersonInfoWrapper.
+ (id)queryForNativeSignupWithObject:(GTLPersonendpointPersonInfoWrapper *)object;

// Method: personendpoint.personExists
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointBooleanWrapper.
+ (id)queryForPersonExistsWithEmail:(NSString *)email;

// Method: personendpoint.replacePersonCards
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
+ (id)queryForReplacePersonCardsWithObject:(GTLPersonendpointPersonCardsListWrapper *)object
                                  personId:(long long)personId;

// Method: personendpoint.saveGCMMessage
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
+ (id)queryForSaveGCMMessageWithGcmRegistrationId:(NSString *)gcmRegistrationId
                                       gcmMessage:(NSString *)gcmMessage;

// Method: personendpoint.socialSignup
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointPersonInfoWrapper.
+ (id)queryForSocialSignupWithObject:(GTLPersonendpointPersonInfoWrapper *)object;

// Method: personendpoint.updateDeviceInfo
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointDeviceInfo.
+ (id)queryForUpdateDeviceInfoWithObject:(GTLPersonendpointDeviceInfo *)object;

@end
